### ISSUE TITLE
Johnny Five backpack

### ISSUE THREAD

**Issue by techniq** [rwaldron/arduino-adc-io-expander#1]
Is this usable/available as a johnny-five backpack?  

I'm guessing a javascript / johnny-five library will need to be created to expose this over I2C similarly to https://github.com/ajfisher/node-pixel or https://github.com/rwaldron/j5-ds-touch.  I also came across this guide while trying to understand backpacks more - https://gist.github.com/rwaldron/769068fbbc9b433768dd

I'm looking to read a potentiometer on Raspberry PI (`analogRead`) and while I could get a chip to do it, I have some Arduinos laying around and this looked promising.

**Comment by rwaldron** [comment]
> I'm guessing a javascript / johnny-five library will need to be created to expose this over I2C similarly 

You are correct that such a thing would need to exist. My plan to was write an `Expander` controller for Johnny-Five to interact with microcontrollers running this firmware.
